# Generated by Django 3.2.12 on 2022-08-01 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220801_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='profile_picture',
            new_name='profile_image',
        ),
    ]
